### ISSUE TITLE
Switch to using lawn mower integration

### ISSUE THREAD

**Issue by clau-bucur** [Whytey/moebot-hass-integration#15]
Home Assistant 2023.9 added built-in support for lawn mowers: https://www.home-assistant.io/integrations/lawn_mower/

It would be great to switch from using a vacuum entity to a proper lawn mower.

**Comment by SitramSoft** [comment]
That would be a nice feature!

**Comment by Whytey** [comment]
It is in the works. 👍

**Comment by SitramSoft** [comment]
> It is in the works. 👍

Awesome! Thanks for taking the time to maintain this repo.

**Comment by Whytey** [comment]
A lawn mower component is now available in master but not yet released.
