### ISSUE TITLE
Not available on HACS?

### ISSUE THREAD

**Issue by longshadowdev** [Whytey/moebot-hass-integration#17]
Hello! I have followed the readme but can't find it in HACS. I see a whole lot of things including 4 lawnmower related services but not Moebot. Has your publish integration broken?

**Comment by longshadowdev** [comment]
I guess after reading a bit more, there are a whole lot of (undocumented?) steps not mentioned. Like adding this repo to HACS, adding the Moebot to a Tuya app to get its Device ID and Local Key. And maybe other things? I'm going to give up for now but if there's a place with a guide of getting this working please let me know.

**Comment by Whytey** [comment]
Hi,

I will take a look at the instructions and clean them up.  You are right,
you need to add the moebot-hass-integration repository into HACS before you
can install it.

**Comment by Whytey** [comment]
This has been resolved in #31.  Potential improvements, particularly around the identification of the Local Key may be provided in future, though the chances are slim.  Sorry.
