### ISSUE TITLE
Start stop Moebot from HA

### ISSUE THREAD

**Issue by mickcomp** [Whytey/moebot-hass-integration#18]
not really an issue but more of a request.   Would be great to have the ability to start and stop the mower from HA so automations can be used and not rely on the tuya app.

**Comment by PeteRepeat77** [comment]
I can already start and stop the mower from home assistant in the current version that has been released. Am I miss understanding what you are asking for?

**Comment by mickcomp** [comment]
not at all thats what i am asking.  I may have missed it in the documentation? are you able to point me in the right direction?

**Comment by Whytey** [comment]
Hi,

Under the integration, there should be a Vacuum entity that you can
control. Pictures attached to give some additional guidance...

**Comment by Whytey** [comment]
![Screenshot_20240402-205647~2](https://github.com/Whytey/moebot-hass-integration/assets/876620/05fc5c70-b0df-4d0f-8105-efd6220b82da)
![Screenshot_20240402-205659~2](https://github.com/Whytey/moebot-hass-integration/assets/876620/81735703-5d1e-4fb9-b03a-03548a887d98)

**Comment by mickcomp** [comment]
Ok never thought to click on Moebot I found the options.  Thanks again!
