### ISSUE TITLE
Add integration icon

### ISSUE THREAD

**Issue by clau-bucur** [Whytey/moebot-hass-integration#34]
You know what this great integration needs now? An icon!

One example: https://cdn1.iconfinder.com/data/icons/garden-tools-elasto-font-next-2020/16/04_lawn-mower-robot-512.png
![5993782.png](https://github.com/user-attachments/assets/098b7d5b-f701-431e-96d0-240420850b10)

**Comment by Whytey** [comment]
Haha, give a man a rest @clau-bucur  :smile: 

Actually, I have looked into this - you mean for the icon here?

![image](https://github.com/user-attachments/assets/57b9db3e-f9cb-45e0-bc30-d95afe23979e)

That requires me to upload an icon the 'brands' repo at https://github.com/home-assistant/brands first.  

I will see what I can do :+1:

**Comment by clau-bucur** [comment]
> Haha, give a man a rest @clau-bucur  :smile: 

Sorry! 😇🤣

> Actually, I have looked into this - you mean for the icon here?
> 
> ![image](https://github.com/user-attachments/assets/57b9db3e-f9cb-45e0-bc30-d95afe23979e)
> 
> That requires me to upload an icon the 'brands' repo at https://github.com/home-assistant/brands first.  
> 
> I will see what I can do :+1: 

Yes, that's what I was talking about.
Would be neat to have a nice looking icon there instead of the 'broken' one.

Thanks alot for your work with this.

**Comment by Whytey** [comment]
PR for the brands repo is available at https://github.com/home-assistant/brands/pull/5669

I am worried since I don't meet the expected minimum size for the images - but I have just grabbed suitable images from the web.  If it gets rejects I will have to increase the sizes - which is less than ideal.

**Comment by clau-bucur** [comment]
Very nice!
![image](https://github.com/user-attachments/assets/6badc4b3-9d1f-4ae9-9b6c-6170cb0f5ca6)

**Comment by Whytey** [comment]
Yes, it looks good. I'm not seeing the icon come through though, still get
a 404. I'll give it a day or so incase there is some other release process
or something.
