### ISSUE TITLE
Allow setting tinytuya version

### ISSUE THREAD

**Issue by clau-bucur** [Whytey/moebot-hass-integration#6]
Thanks for this integration, I've just started using it!

My robot is however not coming online in the integration, even though it's alive and kicking.
I can control it by using the pymoebot library.

The robot is using version 3.4 and I see the library is hardcoding 3.3.
Would it be possible to make it configurable?

**Comment by Whytey** [comment]
Hi @clau-bucur ,

When you talk about the version being used - I assume you are referring to the TUYA protocol version?  Can you confirm?

Cheers,
Whytey

**Comment by Whytey** [comment]
Also, could you please see what error messages you might be seeing in the Home-Assistant logs and paste them here?

**Comment by clau-bucur** [comment]
> When you talk about the version being used - I assume you are referring to the TUYA protocol version? Can you confirm?

That's correct.

Looking at the logs I see only this entry, flooding the logs:
`
2023-06-07 08:29:22.924 ERROR (Thread-11 (listen)) [pymoebot] Error from device: {'Error': 'Network Error: Unable to Connect', 'Err': '901', 'Payload': None}
`

**Comment by Whytey** [comment]
Hmmm, you're not the first to experience this issue - someone on Reddit had the same problem and I haven't had much chance to resolve it yet.

Just out of curiosity, what version of Python is your Home Assistant instance running in?  You can find this from Settings > System > Repairs > Overflow menu (three dots) > System Information.

Should be a view like:
![image](https://github.com/Whytey/moebot-hass-integration/assets/876620/c08a6e59-d055-4baf-b6af-bdeae20959ee)

**Comment by clau-bucur** [comment]
Here it is:
![image](https://github.com/Whytey/moebot-hass-integration/assets/47672949/4eff81c2-c322-4e4f-b933-98e314ee59a5)

But I have a feeling if the protocol version can be changed, this log error would go away.
At least testing pymoebot locally where I could change the protocol version, did not have this issue and I could interact with the mower.

**Comment by Whytey** [comment]
> I have a feeling if the protocol version can be changed, this log error would go away.

We could test that.

1. On your machine running hacks, go to your config directory `/config`.
2. Find the pymoebot source in the `deps` folder at `deps/lib/python3.10/site-packages/pymoebot`
3. Change the protocol version from 3.3 to 3.4 in the `__init__()` method.
4. Restart home assistant.

Let me know how that goes.  If it doesn't work, you can always revert it back.

Cheers,
Whytey

**Comment by clau-bucur** [comment]
I'm afraid the `deps` folder is empty. Could it be due to I'm running HA OS installation?

**Comment by Whytey** [comment]
I'll have to look into where Hass OS stored them. Sorry, I'm a bit new to
this and probably chose a slightly tougher nut to crack.

**Comment by clau-bucur** [comment]
I'm searching the same in the meanwhile. Found no trace of the pymoebot folder yet though!

**Comment by clau-bucur** [comment]
Found it, with the help of https://community.home-assistant.io/t/access-python-core-folder-of-raspberry-pi-ha-os/453018.
It's located under `/usr/local/lib/python3.10/site-packages/pymoebot`.

I've changed the protocol version and voila!
![image](https://github.com/Whytey/moebot-hass-integration/assets/47672949/f33e8cb7-70f4-4864-8003-d73fd587c4db)

**Comment by Whytey** [comment]
Well, well!  That is exciting.

I wonder what, if anything, if possible with the firmware version you're running (that provide TUYA 3.4) vs the firmware I have (that provides TUYA 3.3)!?

Thanks for helping.  As soon as I am out of this busy work period I will ensure we update the integration and pymoebot library to address this.  We should leave this issue open until then.

In the meantime, I am keen to hear if you have control working and whether your mower behaves OK while running the integration.

**Comment by clau-bucur** [comment]
It is exciting indeed, and you made it possible!

Not sure what you mean regarding the differences between 3.4 vs 3.3?

Will get back with feedback. First I'll create a couple of scripts for `mow` and `park` to handle transitions regardless of the current state the mower is. Only by having that, the mower can be automated. I'll add the scripts, once I have them, to #7 just for reference.

**Comment by clau-bucur** [comment]
Ok, I can say everything works good. By overriding the Tuya protocol version and using the scripts I added at #7 I have no problems automating the mower.

Somehow the library got overwritten and the protocol reverted to 3.3 so I had to change it again.
Adding this option would be really helpful here.

Thanks.

**Comment by Whytey** [comment]
Closing this.  The pymoebot library tries to auto-detect the protocol version.  If this doesn't provide appropriate coverage in the future, we may look to rectify this.
